import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import localFont from "next/font/local";
import Header from '../app/Components/header';
import "./globals.css";

// import SmoothScroll from './Components/smothScroll/SmoothScroll';
const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // Add weights as needed
});
export const metadata: Metadata = {
  title: "Adevnt Stagging Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/xcp5ptr.css"/>
      </head>
      <body className={`${inter.className} ${roboto.className}`}>
        {/* <SmoothScroll /> */}
        <Header/>
        <main>{children}</main>
        <div className="overlay"></div>
      </body>
    </html>
  );
}